import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import theme from "../../theme";
import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { LayoutContainerStyle } from "../../styles/layoutStyles";

export const metadata: Metadata = {
  title: "Nepal Gem and Jewelry Association",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <LayoutContainerStyle>{children}</LayoutContainerStyle>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
