import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "../../components/navbar/Navbar";
import FooterBar from "../../components/footer/Footer";
import { Analytics } from "@vercel/analytics/react";

import "./global.css";

export const metadata: Metadata = {
  title: "Nepal Gem and Jewelry Association",
  description: "Generated by create next app",
};

const poppins = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='scroll-smooth' lang='en'>
      <body className={`${poppins.className} bg-background-primary`}>
        <Navbar />
        {children}
        <Analytics />
        <FooterBar />
      </body>
    </html>
  );
}
