import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./global.css";

export const metadata: Metadata = {
  title: "Nepal Gem and Jewelry Association",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} bg-background-primary`}>
        {children}
      </body>
    </html>
  );
}
